#!/usr/bin/python

'''
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
'''

import sys

def main():

    Current = 2
    Previous = 1
    Temp = 0
    Sum = 0

    # Add Fibonacci numbers until we hit 4,000,000
    while Current <= 4000000:
        Sum = Sum + Current

        # Loop three times as only every third Fibonacci number
        # is even
        for i in range(0,3):
            Temp = Current
            Current = Current + Previous
            Previous = Temp

    # Print the answer
    print(Sum)

    sys.exit(0)

if __name__ == "__main__":
    main()
